language: erlang
branches:
  only:
    - master

cache:
  - ~/.cache/rebar3

otp_release:
  - 21.0
  - 20.3
  - 19.3

script:
  - rebar3 ct
  - rebar3 dialyzer

notifications:
  email: mongoose-im@erlang-solutions.com
